# [package]
# name = "nat20_rs" # the name of the package
# version = "0.1.0"    # the current version, obeying semver

[workspace]
members = [
    "engine", "gui"
]

[patch.crates-io]
polyanya = { git = "https://github.com/MadsWedendahlKruse/polyanya", branch = "fix-path-with-height-oob" }